#---------------------------
# 全局
#---------------------------
favicon: https://cdn.zengjunyin.com/icon/favicon-dog.svg

apple_touch_icon: https://cdn.zengjunyin.com/icon/favicon-dog.svg

tab_title_separator: " - "

force_https: true

# 代码
code:
  copy_btn: true
  language:
    enable: true
    default: "bash"
  highlight:
    enable: true
    line_number: true
    lib: "highlightjs"
    highlightjs:
      # https://highlightjs.org/static/demo/
      style: "Arduino Light"
      style_dark: "Androidstudio"
    prismjs:
      # https://prismjs.com/
      style: "default"
      style_dark: "tomorrow night"
      # true：高亮本地生成（只支持部分 prismjs 插件） 丨 false：高亮在浏览器通过 js 生成
      preprocess: true

# 额外功能
fun_features:
  # 打字机
  typing:
    enable: false
    typeSpeed: 70
    cursorChar: "_"
    loop: false
    # 在指定页面开启
    scope: []
  # 锚图标
  anchorjs:
    enable: true
    element: h1,h2,h3,h4,h5,h6
    placement: right
    # Options: hover | always | touch
    visible: always
    # Option：§ | # | ❡
    icon: ""
  # 加载进度条
  progressbar:
    enable: true
    height_px: 3
    color: "#29d"
    # https://github.com/rstacruz/nprogress
    options: { showSpinner: false, trickleSpeed: 100 }

# 暗色模式
dark_mode:
  enable: true
  # Options: auto | light | dark
  default: auto

# 颜色
color:
  # 全局背景色
  body_bg_color: "#eee"
  body_bg_color_dark: "#181c27"
  # 顶部菜单背景色
  navbar_bg_color: "#2f4154"
  navbar_bg_color_dark: "#1f3144"
  # 顶部菜单字体色
  navbar_text_color: "#fff"
  navbar_text_color_dark: "#d0d0d0"
  # 副标题字体色
  subtitle_color: "#fff"
  subtitle_color_dark: "#d0d0d0"
  # 全局字体色
  text_color: "#3c4858"
  text_color_dark: "#c4c6c9"
  # 全局次级字体色（摘要、简介等位置）
  sec_text_color: "#718096"
  sec_text_color_dark: "#a7a9ad"
  # 主面板背景色
  board_color: "#fff"
  board_color_dark: "#252d38"
  # 文章正文字体色
  post_text_color: "#2c3e50"
  post_text_color_dark: "#c4c6c9"
  # 文章正文标题字体色（h1 h2 h3...）
  post_heading_color: "#1a202c"
  post_heading_color_dark: "#c4c6c9"
  # 文章超链接字体色
  post_link_color: "#0366d6"
  post_link_color_dark: "#1589e9"
  # 超链接悬浮时字体色
  link_hover_color: "#30a9de"
  link_hover_color_dark: "#30a9de"
  # 超链接悬浮背景色
  link_hover_bg_color: "#f8f9fa"
  link_hover_bg_color_dark: "#364151"
  # 分隔线和表格边线的颜色
  line_color: "#eaecef"
  line_color_dark: "#435266"
  # 滚动条颜色
  scrollbar_color: "#c4c6c9"
  scrollbar_color_dark: "#687582"
  # 滚动条悬浮颜色
  scrollbar_hover_color: "#a6a6a6"
  scrollbar_hover_color_dark: "#9da8b3"
  # 按钮背景色
  button_bg_color: "transparent"
  button_bg_color_dark: "transparent"
  # 按钮悬浮背景色
  button_hover_bg_color: "#f2f3f5"
  button_hover_bg_color_dark: "#46647e"

# 字体
font:
  font_size: 17px
  font_family: Roboto, Noto Sans SC, sans-serif;
  letter_spacing: 0.06em
  code_font_size: 85%

# 自定义
custom_js:
custom_css: /css/sky.css
custom_head: <link rel="preconnect" href="https://fonts.googleapis.com"><link rel="preconnect" href="https://fonts.gstatic.com" crossorigin><link href="https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@100;300;400;500;700;900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
custom_html: ''

# 网页访问统计
web_analytics:
  enable: true
  baidu: 4c458d1750ea58f8c9d61bc90c4d82dd
  google:
  gtag:
  tencent:
    sid:
    cid:
  woyaola:
  cnzz:
  leancloud:
    app_id:
    app_key:
    server_url:
    path: window.location.pathname
    ignore_local: false

# 懒加载
lazyload:
  enable: true
  loading_img: https://cdn.zengjunyin.com/blogstatic/images/loading.gif
  onlypost: true
  offset_factor: 2

# 图标库
iconfont: https://at.alicdn.com/t/font_3048099_fausv5mswvk.css

#---------------------------
# 页头
#---------------------------
# 导航栏
navbar:
  blog_title: "归梦の博客"
  # 毛玻璃特效
  ground_glass:
    enable: false
    # 模糊像素
    px: 3
    alpha: 0.7
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-Archive" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category_fill" }
    - { key: "bber", link: "/bber/", icon: "iconfont icon-love" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user" }
    - { key: "links", link: "/links/", icon: "iconfont icon-link_fill" }
search:
  enable: true
  path: /local-search.xml
  generate_path: /local-search.xml
  # Options: post | page | all
  field: post
  # 是否扫描正文
  content: true

# 首屏图片
banner:
  # 视差滚动
  parallax: true
  # 最小的宽高比
  width_height_ratio: 1.0
# 向下滚动的箭头
scroll_down_arrow:
  enable: true
  banner_height_limit: 80
  scroll_after_turning_page: true
# 向顶部滚动的箭头
scroll_top_arrow:
  enable: true
open_graph:
  enable: false
  twitter_card: summary_large_image
  twitter_id:
  twitter_site:
  google_plus:
  fb_admins:
  fb_app_id:

#---------------------------
# 页脚
#---------------------------
footer:
  content: '
    <a target="_blank" href="https://hexo.io" title="框架 Hexo"><img src="https://cdn.zengjunyin.com/blogstatic/images/Frame-Hexo-blue.svg"></a>
    <a target="_blank" href="https://github.com/fluid-dev/hexo-theme-fluid" title="主题 Fluid"><img src="https://cdn.zengjunyin.com/blogstatic/images/Theme-Fluid-lightgrey.svg"></a>
    <br/>
    <p></p> 
  '
  statistics:
    enable: false
    source: "busuanzi"
  # 备案信息
  beian:
    enable: true
    # ICP证号
    icp_text: 闽ICP备2021019269号
    # 公安备案号
    police_text:
    # 公安备案的编号
    police_code:
    # 公安备案的图片
    police_icon:

#---------------------------
# 首页
#---------------------------
index:
  banner_img: https://cdn.zengjunyin.com/blogstatic/images/background.jpg
  banner_img_height: 100
  banner_mask_alpha: 0.3
  # 副标题
  slogan:
    enable: true
    text: "My Pure Life"
    api:
      enable: false
      url: ""
      # Available: GET | POST | PUT
      method: "GET"
      headers: {}
      keys: []
  # 自动截取文章摘要
  auto_excerpt:
    enable: false
  # Available: _blank | _self
  post_url_target: _self
  post_meta:
    date: true
    category: true
    tag: false
  # 文章通过 sticky 排序后，在首页文章标题前显示图标
  post_sticky:
    enable: true
    icon: "iconfont icon-iconfonticonfonti2copy"

#---------------------------
# 文章页
#---------------------------
post:
  banner_img: https://cdn.zengjunyin.com/blogstatic/images/background.jpg
  banner_img_height: 70
  banner_mask_alpha: 0.3
  default_index_img:
  # 元信息
  meta:
    author:
      enable: true
    date:
      enable: true
      # http://momentjs.cn/docs/#/parsing/string-format/
      format: "LL a"
    wordcount:
      enable: true
    min2read:
      enable: false
      awl: 2
      wpm: 60
    views:
      enable: false
      source: "busuanzi"
  updated:
    enable: false
    date_format: "LL a"
    relative: false
    # Options: default | primary | info | success | warning | danger | light
    note_class: info
  # 侧边栏展示当前分类下的文章
  category_bar:
    enable: false
    specific: false
    # Options: left | right
    placement: left
    # Options: date | title | or other field of front-matter
    post_order_by: "date"
    post_limit: 0
  toc:
    enable: false
    # Options: left | right
    placement: right
    headingSelector: "h1,h2,h3,h4,h5,h6"
    collapseDepth: 0
  copyright:
    enable: true
    # Options: BY | BY-SA | BY-ND | BY-NC | BY-NC-SA | BY-NC-ND
    license: 'BY-NC'
    author:
      enable: true
    post_date:
      enable: true
      format: "LL"
    update_date:
      enable: false
      format: "LL"
  # 文章底部上一篇下一篇功能
  prev_next:
    enable: true
  # 文章图片标题
  image_caption:
    enable: true
  # 图片可点击放大
  image_zoom:
    enable: true
    img_url_replace: ['/zoom', '']
  # 脚注语法
  footnote:
    enable: false
    header: ''
  # 数学公式
  math:
    enable: false
    specific: false
    # Options: mathjax | katex
    engine: mathjax
  # 流程图
  mermaid:
    enable: false
    specific: false
    options: { theme: 'default' }
  # 评论插件
  comments:
    enable: true
    # Options: utterances | disqus | gitalk | valine | waline | changyan | livere | remark42 | twikoo | cusdis
    type: twikoo

#---------------------------
# 评论插件
#---------------------------
utterances:
  repo:
  issue_term: pathname
  label: utterances
  theme: github-light
  theme_dark: github-dark

disqus:
  shortname:
  disqusjs: false
  apikey:

gitalk:
  clientID:
  clientSecret:
  repo:
  owner:
  admin: ['name']
  language: zh-CN
  labels: ['Gitalk']
  perPage: 10
  pagerDirection: last
  distractionFreeMode: false
  createIssueManually: true
  proxy: https://cors-anywhere.azm.workers.dev/https://github.com/login/oauth/access_token

valine:
  appId:
  appKey:
  path: window.location.pathname
  placeholder:
  avatar: 'retro'
  meta: ['nick', 'mail', 'link']
  requiredFields: []
  pageSize: 10
  lang: 'zh-CN'
  highlight: false
  recordIP: false
  serverURLs: ''
  emojiCDN:
  emojiMaps:
  enableQQ: false

waline:
  serverURL: ''
  path: window.location.pathname
  placeholder:
  meta: ['nick', 'mail', 'link']
  requiredMeta: ['nick']
  lang: 'zh-CN'
  emoji: ['https://cdn.jsdelivr.net/gh/walinejs/emojis/weibo']
  dark: 'html[data-user-color-scheme="dark"]'
  avatar: 'retro'
  avatarCDN: 'https://seccdn.libravatar.org/avatar/'
  avatarForce: false
  wordLimit: 0
  pageSize: 10
  highlight: true

changyan:
  appid: ''
  appkey: ''

livere:
  uid: ''

remark42:
  host:
  site_id:
  max_shown_comments: 10
  locale: zh
  components: ['embed']

twikoo:
  envId: twikoo-8gdiepwi8607bd4e
  region: ap-guangzhou
  path: window.location.pathname

cusdis:
  host:
  app_id:
  lang: zh-cn

#---------------------------
# 归档页
#---------------------------
archive:
  banner_img: https://cdn.zengjunyin.com/blogstatic/images/background.jpg
  banner_img_height: 70
  banner_mask_alpha: 0.3

#---------------------------
# 分类页
#---------------------------
category:
  enable: true
  banner_img: https://cdn.zengjunyin.com/blogstatic/images/background.jpg
  banner_img_height: 70
  banner_mask_alpha: 0.3
  # 排序字段
  # Options: length | name
  order_by: "-length"
  # 折叠深度
  collapse_depth: 0
  # 文章的排序字段
  # Options: date | title | or other field of front-matter
  post_order_by: "-date"
  post_limit: 0

#---------------------------
# 标签页
#---------------------------
tag:
  enable: false
  banner_img: https://cdn.zengjunyin.com/blogstatic/images/background.jpg
  banner_img_height: 70
  banner_mask_alpha: 0.3
  tagcloud:
    min_font: 24
    max_font: 30
    unit: px
    start_color: "#BBBBEE"
    end_color: "#337ab7"

#---------------------------
# 关于页
#---------------------------
about:
  enable: true
  banner_img: https://cdn.zengjunyin.com/blogstatic/images/background.jpg
  banner_img_height: 70
  banner_mask_alpha: 0.3
  avatar: /image/avatar.jpg
  name: "归梦"
  intro: "Nice To Meet You!"
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/adelasky", tip: "GitHub" }
    - { class: "iconfont icon-mail_fill", link: "mailto:zengjunyin@foxmail.com", tip: "Mail" }

#---------------------------
# 自定义页
#---------------------------
page:
  banner_img: https://cdn.zengjunyin.com/blogstatic/images/background.jpg
  banner_img_height: 70
  banner_mask_alpha: 0.3

#---------------------------
# 404页
#---------------------------
page404:
  enable: true
  banner_img: https://cdn.zengjunyin.com/blogstatic/images/background.jpg
  banner_img_height: 100
  banner_mask_alpha: 0.3
  redirect_delay: 5000

#---------------------------
# 友链页
#---------------------------
links:
  enable: true
  banner_img: https://cdn.zengjunyin.com/blogstatic/images/background.jpg
  banner_img_height: 70
  banner_mask_alpha: 0.3
  items:
    - {
      title: "山川行貉",
      intro: "快让我在雪地上撒点儿野.",
      link: "https://www.scxho.cn",
      avatar: "https://cravatar.cn/avatar/24e54d6a6ac9c59d9d5ee44c825b8c0a?s=100&r=G&d=mm"
    }
    - {
      title: "Vian",
      intro: "想要的都拥有，得不到的都释怀...",
      link: "https://vian.top",
      avatar: "https://vian.top/avatar.ico"
    }
    - {
      title: "Fluid Blog",
      intro: "主题博客",
      link: "https://hexo.fluid-dev.com/",
      avatar: "https://cdn.zengjunyin.com/blogstatic/images/fluid_link.png"
    }
    - {
      title: "Fluid Docs",
      intro: "主题使用指南",
      link: "https://hexo.fluid-dev.com/docs/",
      avatar: "https://cdn.zengjunyin.com/blogstatic/images/fluid_link.png"
    }
    - {
      title: "Fluid Repo",
      intro: "主题 GitHub 仓库",
      link: "https://github.com/fluid-dev/hexo-theme-fluid",
      avatar: "https://cdn.zengjunyin.com/blogstatic/images/fluid_link.png"
    }
  onerror_avatar: https://cdn.zengjunyin.com/blogstatic/images/linkavatar.png
  custom:
    enable: false
    content: ''
  comments:
    enable: false
    # Options: utterances | disqus | gitalk | valine | waline | changyan | livere | remark42 | twikoo | cusdis
    type: twikoo

#---------------------------
# 静态地址
#---------------------------
static_prefix:

  internal_js: /js
  internal_css: /css
  internal_img: /img

  anchor: https://lib.baomitu.com/anchor-js/4.3.1/

  github_markdown: https://lib.baomitu.com/github-markdown-css/4.0.0/

  jquery: https://lib.baomitu.com/jquery/3.6.0/

  bootstrap: https://lib.baomitu.com/twitter-bootstrap/4.6.1/

  prismjs: https://lib.baomitu.com/prism/1.26.0/

  tocbot: https://lib.baomitu.com/tocbot/4.18.0/

  typed: https://lib.baomitu.com/typed.js/2.0.12/

  fancybox: https://lib.baomitu.com/fancybox/3.5.7/

  nprogress: https://lib.baomitu.com/nprogress/0.2.0/

  mathjax: https://lib.baomitu.com/mathjax/3.2.0/

  katex: https://lib.baomitu.com/KaTeX/0.15.2/

  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/

  clipboard: https://lib.baomitu.com/clipboard.js/2.0.10/

  mermaid: https://lib.baomitu.com/mermaid/8.13.10/

  valine: https://lib.baomitu.com/valine/1.4.16/

  waline: https://lib.baomitu.com/waline/1.5.2/

  gitalk: https://lib.baomitu.com/gitalk/1.7.2/

  disqusjs: https://lib.baomitu.com/disqusjs/1.3.0/

  twikoo: https://cdn.staticfile.org/twikoo/1.5.10/

  hint: https://lib.baomitu.com/hint.css/2.7.0/