favicon: /image/favicon-dog.svg

apple_touch_icon: /image/favicon-dog.svg

force_https: true

code:
  highlight:
    highlightjs:
      style: "Purebasic"
      style_dark: "Obsidian"

fun_features:
  typing:
    enable: false
  anchorjs:
    placement: right
    visible: always

dark_mode:
  default: dark

font:
  font_size: 17px
  font_family: Roboto, Noto Sans SC, sans-serif;
  letter_spacing: 0.06em

custom_js:
custom_css: /css/sky.css
custom_head: '<link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Noto+Sans+SC:wght@100;300;400;500;700;900&family=Roboto:ital,wght@0,100;0,300;0,400;0,500;0,700;0,900;1,100;1,300;1,400;1,500;1,700;1,900&display=swap" rel="stylesheet">
  <meta name="referrer" content="no-referrer">
  <meta name="baidu-site-verification" content="code-1oLGzDasxv" />
'

web_analytics:
  enable: true
  baidu: 4c458d1750ea58f8c9d61bc90c4d82dd

lazyload:
  loading_img: /image/loading.gif
  onlypost: true

iconfont: https://at.alicdn.com/t/font_3048099_fausv5mswvk.css

navbar:
  blog_title: "归梦の博客"
  menu:
    - { key: "home", link: "/", icon: "iconfont icon-home-fill" }
    - { key: "archive", link: "/archives/", icon: "iconfont icon-Archive" }
    - { key: "category", link: "/categories/", icon: "iconfont icon-category_fill" }
    - { key: "说说", link: "/bber/", icon: "iconfont icon-love" }
    - { key: "about", link: "/about/", icon: "iconfont icon-user" }
    - { key: "links", link: "/links/", icon: "iconfont icon-link_fill" }

open_graph:
  enable: false

footer:
  content: '
    <a target="_blank" href="https://hexo.io" title="框架 Hexo"><img src="/image/Frame-Hexo-blue.svg"></a>
    <a target="_blank" href="https://github.com/fluid-dev/hexo-theme-fluid" title="主题 Fluid"><img src="/image/Theme-Fluid-lightgrey.svg"></a>
    <br/>
    <p></p> 
  '

  beian:
    enable: true
    icp_text: 闽ICP备2021019269号

index:
  banner_img: image/background_light.jpg
  slogan:
    enable: true
    text: "只是一种漠不关心的存在"
  auto_excerpt:
    enable: false
  post_meta:
    date: true
    category: true
    tag: false
  post_sticky:
    enable: true
    icon: "iconfont icon-iconfonticonfonti2copy"

post:
  banner_img: image/background_light.jpg
  meta:
    author:
      enable: true
    min2read:
      enable: false
  category_bar:
    enable: false
  toc:
    enable: false
  copyright:
    enable: true
    license: 'BY-NC'
  image_zoom:
    enable: true
    img_url_replace: ['@1000w.webp', '']
  comments:
    enable: true
    type: twikoo

twikoo:
  envId: twikoo-8gdiepwi8607bd4e
  region: ap-guangzhou
  path: window.location.pathname

archive:
  banner_img: image/background_light.jpg

category:
  banner_img: image/background_light.jpg

tag:
  enable: false

about:
  banner_img: image/background_light.jpg
  avatar: /image/avatar.jpg
  name: "归梦"
  intro: "虽无言,却风雪而立。虽无言,却花满枝头。虽无言,却兀自凋零。"
  icons:
    - { class: "iconfont icon-github-fill", link: "https://github.com/adelasky", tip: "GitHub" }
    - { class: "iconfont icon-mail_fill", link: "mailto:zengjunyin@foxmail.com", tip: "Mail" }

page:
  banner_img: image/background_light.jpg

page404:
  enable: false

links:
  banner_img: image/background_light.jpg
  items:
    - {
      title: "山川行貉",
      intro: "快让我在雪地上撒点儿野.",
      link: "https://www.scxho.cn",
      avatar: "https://scxho.cn/1.png"
    }
    - {
      title: "Vian",
      intro: "想要的都拥有，得不到的都释怀...",
      link: "https://vian.top",
      avatar: "https://vian.top/avatar.ico"
    }
    - {
      title: "窥见天光",
      intro: "梦随风万里...",
      link: "https://blog.lovetianyu.com",
      avatar: "https://blog.lovetianyu.com/upload/2022/04/6b8e3fa1b9bfb5f22ea8869d0284bcba.jpg"
    }
    - {
      title: "阿锋的小宇宙",
      intro: "沧海一粟，微亮渺小一只虫。",
      link: "https://feng.pub",
      avatar: "https://feng.pub/avatar/i_200_200.jpg"
    }
  onerror_avatar: /image/linkavatar.png

static_prefix:
  twikoo: https://cdn.staticfile.org/twikoo/1.5.10/